import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens from Frontend.html
        "on-background": "#1b1b1b",
        "tertiary-fixed": "#e3e2df",
        "tertiary-fixed-dim": "#c7c6c3",
        secondary: "#735c00",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#001b3c",
        "on-secondary": "#ffffff",
        "surface-container": "#f0eded",
        tertiary: "#1f201e",
        "tertiary-container": "#343533",
        "on-surface": "#1b1b1b",
        "on-secondary-container": "#745c00",
        "on-primary-fixed-variant": "#30476a",
        "surface-container-high": "#eae7e7",
        "error-container": "#ffdad6",
        background: "#fcf9f8",
        "primary-fixed": "#d5e3ff",
        "on-surface-variant": "#44474e",
        "outline-variant": "#c4c6cf",
        "on-primary-container": "#879ec6",
        "surface-container-highest": "#e5e2e1",
        outline: "#74777f",
        error: "#ba1a1a",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed": "#241a00",
        primary: "#031f41",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffe088",
        "inverse-primary": "#b0c7f1",
        "on-error-container": "#93000a",
        "surface-dim": "#dcd9d9",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#fed65b",
        "surface-tint": "#485f84",
        surface: "#fcf9f8",
        "on-tertiary-fixed-variant": "#464744",
        "surface-container-low": "#f6f3f2",
        "surface-variant": "#e5e2e1",
        "on-tertiary-fixed": "#1b1c1a",
        "primary-fixed-dim": "#b0c7f1",
        "primary-container": "#1d3557",
        "on-secondary-fixed-variant": "#574500",
        "inverse-surface": "#313030",
        "on-tertiary-container": "#9d9d9a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "24px",
        "section-margin": "120px",
        "card-gap": "24px",
        unit: "8px",
        gutter: "32px",
        "container-padding-desktop": "80px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-libre-caslon)", "serif"],
        "display-lg": ["var(--font-libre-caslon)", "serif"],
        "body-lg": ["var(--font-manrope)", "sans-serif"],
        "title-lg": ["var(--font-manrope)", "sans-serif"],
        "headline-lg": ["var(--font-libre-caslon)", "serif"],
        "headline-md": ["var(--font-libre-caslon)", "serif"],
        "label-sm": ["var(--font-manrope)", "sans-serif"],
        "body-md": ["var(--font-manrope)", "sans-serif"],
        "label-md": ["var(--font-manrope)", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "30px", fontWeight: "400" }],
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
